/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.JoaProduto;
import dao.ProdutoDAO;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author User
 */
public class JDlgProdutoNovoIA extends javax.swing.JDialog {

    MaskFormatter mascaraValorC, mascaraValorV;
     ProdutoDAO produtoDAO;
     ProdutosControle produtoControle;
     JoaProduto produto;
    /**
     * Creates new form JDlgProdutoNovoIA
     */
    public JDlgProdutoNovoIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Util.limparCampos(joa_jTxtCodigo1, joa_jTxtNome, joa_jTxtDescricao, joa_jFmtValorC, joa_jFmtValorV, joa_jCboCategoria);
        setLocationRelativeTo(null);
        setTitle("Cadastro de Produtos");
   
        try {
            mascaraValorC = new MaskFormatter("###.##");
            mascaraValorV = new MaskFormatter("###.##");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgProdutoNovoIA.class.getName()).log(Level.SEVERE, null, ex);
        }
        joa_jFmtValorC.setFormatterFactory(new DefaultFormatterFactory(mascaraValorC));
        joa_jFmtValorV.setFormatterFactory(new DefaultFormatterFactory(mascaraValorV));
    }

    public JoaProduto viewBean() {
        JoaProduto joaProduto = new JoaProduto();
        joaProduto.setIdjoaProduto(Util.strInt(joa_jTxtCodigo1.getText()));
        joaProduto.setJoaNome(joa_jTxtNome.getText());
        joaProduto.setJoaDescricao(joa_jTxtDescricao.getText());
        joaProduto.setJoaValorCompra(Util.strDouble(joa_jFmtValorC.getText()));
        joaProduto.setJoaValorVenda(Util.strDouble(joa_jFmtValorV.getText()));
        joaProduto.setJoaCategoria(joa_jCboCategoria.getSelectedIndex());

        return joaProduto;
    }

    public void beanView(JoaProduto joaProduto) {
        joa_jTxtCodigo1.setText(Util.intStr(joaProduto.getIdjoaProduto()));
        joa_jFmtValorV.setText(Util.doubleStr(joaProduto.getJoaValorVenda()));
        joa_jFmtValorC.setText(Util.doubleStr(joaProduto.getJoaValorCompra()));
        joa_jTxtNome.setText(joaProduto.getJoaNome());
        joa_jTxtDescricao.setText(joaProduto.getJoaDescricao());
        joa_jCboCategoria.setSelectedIndex(joaProduto.getJoaCategoria());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        joa_jBtnOk = new javax.swing.JButton();
        joa_jBtnCancelar = new javax.swing.JButton();
        joa_jFmtValorC = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        joa_jTxtCodigo1 = new javax.swing.JTextField();
        joa_jFmtValorV = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        joa_jCboCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        joa_jTxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        joa_jTxtDescricao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        joa_jBtnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        joa_jBtnOk.setText("OK");
        joa_jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joa_jBtnOkActionPerformed(evt);
            }
        });
        jPanel1.add(joa_jBtnOk);

        joa_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        joa_jBtnCancelar.setText("CANCELAR");
        joa_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joa_jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(joa_jBtnCancelar);

        jLabel3.setText("Valor da Compra");

        jLabel7.setText("Código");

        joa_jTxtCodigo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                joa_jTxtCodigo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                joa_jTxtCodigo1FocusLost(evt);
            }
        });
        joa_jTxtCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joa_jTxtCodigo1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor da Venda");

        joa_jCboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "periferico", "console", "jogo" }));

        jLabel5.setText("Categoria");

        jLabel1.setText("Nome");

        jLabel2.setText("Descrição");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(joa_jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(joa_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(joa_jCboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(joa_jTxtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(94, 94, 94)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(joa_jFmtValorC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(joa_jFmtValorV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(joa_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joa_jTxtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(joa_jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(joa_jCboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(joa_jFmtValorC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(joa_jFmtValorV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joa_jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joa_jBtnOkActionPerformed
        setVisible(false);
        JoaProduto produto = viewBean();

        ProdutoDAO produtoDAO = new ProdutoDAO();

        produtoDAO.insert(produto);
        Util.limparCampos(joa_jTxtCodigo1, joa_jFmtValorV, joa_jFmtValorC, joa_jTxtNome, joa_jTxtDescricao, joa_jCboCategoria);

        // TODO add your handling code here:
    }//GEN-LAST:event_joa_jBtnOkActionPerformed

    private void joa_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joa_jBtnCancelarActionPerformed
        setVisible(false);
        Util.mensagem("Operação Cancelada!");
        Util.limparCampos(joa_jTxtCodigo1, joa_jFmtValorV, joa_jFmtValorC, joa_jTxtNome, joa_jTxtDescricao, joa_jCboCategoria);
        // TODO add your handling code here:
    }//GEN-LAST:event_joa_jBtnCancelarActionPerformed

    private void joa_jTxtCodigo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_joa_jTxtCodigo1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_joa_jTxtCodigo1FocusGained

    private void joa_jTxtCodigo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_joa_jTxtCodigo1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_joa_jTxtCodigo1FocusLost

    private void joa_jTxtCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joa_jTxtCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joa_jTxtCodigo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutoNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutoNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutoNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutoNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgProdutoNovoIA dialog = new JDlgProdutoNovoIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton joa_jBtnCancelar;
    private javax.swing.JButton joa_jBtnOk;
    private javax.swing.JComboBox<String> joa_jCboCategoria;
    private javax.swing.JFormattedTextField joa_jFmtValorC;
    private javax.swing.JFormattedTextField joa_jFmtValorV;
    private javax.swing.JTextField joa_jTxtCodigo1;
    private javax.swing.JTextField joa_jTxtDescricao;
    private javax.swing.JTextField joa_jTxtNome;
    // End of variables declaration//GEN-END:variables
}
