package bean;
// Generated 16/09/2023 15:42:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JoaFuncionario generated by hbm2java
 */
@Entity
@Table(name="joa_funcionario"
    ,catalog="db_juliaalmada"
)
public class JoaFuncionario  implements java.io.Serializable {


     private int idjoaFuncionario;
     private String joaNome;
     private String joaEmail;
     private String joaTelefone;
     private String joaCpf;
     private String joaEmailReserva;
     private String joaEndereco;
     private String joaBairro;
     private String joaPais;
     private String joaCidade;
     private String joaCep;
     private String joaCarteiraTrabalho;
     private String joaDataNascimento;
     private String joaSexo;
     private Set joaVendas = new HashSet(0);

    public JoaFuncionario() {
    }

	
    public JoaFuncionario(int idjoaFuncionario, String joaNome, String joaEmail, String joaTelefone, String joaCpf, String joaEmailReserva, String joaEndereco, String joaBairro, String joaPais, String joaCidade, String joaCep, String joaCarteiraTrabalho, String joaDataNascimento, String joaSexo) {
        this.idjoaFuncionario = idjoaFuncionario;
        this.joaNome = joaNome;
        this.joaEmail = joaEmail;
        this.joaTelefone = joaTelefone;
        this.joaCpf = joaCpf;
        this.joaEmailReserva = joaEmailReserva;
        this.joaEndereco = joaEndereco;
        this.joaBairro = joaBairro;
        this.joaPais = joaPais;
        this.joaCidade = joaCidade;
        this.joaCep = joaCep;
        this.joaCarteiraTrabalho = joaCarteiraTrabalho;
        this.joaDataNascimento = joaDataNascimento;
        this.joaSexo = joaSexo;
    }
    public JoaFuncionario(int idjoaFuncionario, String joaNome, String joaEmail, String joaTelefone, String joaCpf, String joaEmailReserva, String joaEndereco, String joaBairro, String joaPais, String joaCidade, String joaCep, String joaCarteiraTrabalho, String joaDataNascimento, String joaSexo, Set joaVendas) {
       this.idjoaFuncionario = idjoaFuncionario;
       this.joaNome = joaNome;
       this.joaEmail = joaEmail;
       this.joaTelefone = joaTelefone;
       this.joaCpf = joaCpf;
       this.joaEmailReserva = joaEmailReserva;
       this.joaEndereco = joaEndereco;
       this.joaBairro = joaBairro;
       this.joaPais = joaPais;
       this.joaCidade = joaCidade;
       this.joaCep = joaCep;
       this.joaCarteiraTrabalho = joaCarteiraTrabalho;
       this.joaDataNascimento = joaDataNascimento;
       this.joaSexo = joaSexo;
       this.joaVendas = joaVendas;
    }
   
     @Id 

    
    @Column(name="idjoa_funcionario", unique=true, nullable=false)
    public int getIdjoaFuncionario() {
        return this.idjoaFuncionario;
    }
    
    public void setIdjoaFuncionario(int idjoaFuncionario) {
        this.idjoaFuncionario = idjoaFuncionario;
    }

    
    @Column(name="joa_nome", nullable=false, length=45)
    public String getJoaNome() {
        return this.joaNome;
    }
    
    public void setJoaNome(String joaNome) {
        this.joaNome = joaNome;
    }

    
    @Column(name="joa_email", nullable=false, length=45)
    public String getJoaEmail() {
        return this.joaEmail;
    }
    
    public void setJoaEmail(String joaEmail) {
        this.joaEmail = joaEmail;
    }

    
    @Column(name="joa_telefone", nullable=false, length=45)
    public String getJoaTelefone() {
        return this.joaTelefone;
    }
    
    public void setJoaTelefone(String joaTelefone) {
        this.joaTelefone = joaTelefone;
    }

    
    @Column(name="joa_cpf", nullable=false, length=45)
    public String getJoaCpf() {
        return this.joaCpf;
    }
    
    public void setJoaCpf(String joaCpf) {
        this.joaCpf = joaCpf;
    }

    
    @Column(name="joa_emailReserva", nullable=false, length=45)
    public String getJoaEmailReserva() {
        return this.joaEmailReserva;
    }
    
    public void setJoaEmailReserva(String joaEmailReserva) {
        this.joaEmailReserva = joaEmailReserva;
    }

    
    @Column(name="joa_endereco", nullable=false, length=45)
    public String getJoaEndereco() {
        return this.joaEndereco;
    }
    
    public void setJoaEndereco(String joaEndereco) {
        this.joaEndereco = joaEndereco;
    }

    
    @Column(name="joa_bairro", nullable=false, length=45)
    public String getJoaBairro() {
        return this.joaBairro;
    }
    
    public void setJoaBairro(String joaBairro) {
        this.joaBairro = joaBairro;
    }

    
    @Column(name="joa_pais", nullable=false, length=45)
    public String getJoaPais() {
        return this.joaPais;
    }
    
    public void setJoaPais(String joaPais) {
        this.joaPais = joaPais;
    }

    
    @Column(name="joa_cidade", nullable=false, length=45)
    public String getJoaCidade() {
        return this.joaCidade;
    }
    
    public void setJoaCidade(String joaCidade) {
        this.joaCidade = joaCidade;
    }

    
    @Column(name="joa_cep", nullable=false, length=10)
    public String getJoaCep() {
        return this.joaCep;
    }
    
    public void setJoaCep(String joaCep) {
        this.joaCep = joaCep;
    }

    
    @Column(name="joa_carteiraTrabalho", nullable=false, length=45)
    public String getJoaCarteiraTrabalho() {
        return this.joaCarteiraTrabalho;
    }
    
    public void setJoaCarteiraTrabalho(String joaCarteiraTrabalho) {
        this.joaCarteiraTrabalho = joaCarteiraTrabalho;
    }

    
    @Column(name="joa_dataNascimento", nullable=false, length=45)
    public String getJoaDataNascimento() {
        return this.joaDataNascimento;
    }
    
    public void setJoaDataNascimento(String joaDataNascimento) {
        this.joaDataNascimento = joaDataNascimento;
    }

    
    @Column(name="joa_sexo", nullable=false, length=1)
    public String getJoaSexo() {
        return this.joaSexo;
    }
    
    public void setJoaSexo(String joaSexo) {
        this.joaSexo = joaSexo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="joaFuncionario")
    public Set getJoaVendas() {
        return this.joaVendas;
    }
    
    public void setJoaVendas(Set joaVendas) {
        this.joaVendas = joaVendas;
    }




}


