package bean;
<<<<<<< HEAD
// Generated 22/09/2023 23:07:42 by Hibernate Tools 4.3.1
=======
// Generated 22/09/2023 22:28:12 by Hibernate Tools 4.3.1
>>>>>>> 66002ac7362d381f5d40c25923c99ed5d59db325


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JoaProduto generated by hbm2java
 */
@Entity
@Table(name="joa_produto"
    ,catalog="db_juliaalmada"
)
public class JoaProduto  implements java.io.Serializable {


     private int idjoaProduto;
     private String joaNome;
     private String joaDescricao;
     private double joaValorCompra;
     private double joaValorVenda;
     private int joaCategoria;
<<<<<<< HEAD
=======
 
>>>>>>> 66002ac7362d381f5d40c25923c99ed5d59db325

    public JoaProduto() {
    }

	
    public JoaProduto(int idjoaProduto, String joaNome, String joaDescricao, double joaValorCompra, double joaValorVenda, int joaCategoria) {
        this.idjoaProduto = idjoaProduto;
        this.joaNome = joaNome;
        this.joaDescricao = joaDescricao;
        this.joaValorCompra = joaValorCompra;
        this.joaValorVenda = joaValorVenda;
        this.joaCategoria = joaCategoria;
    }
   
     @Id 

    
    @Column(name="idjoa_produto", unique=true, nullable=false)
    public int getIdjoaProduto() {
        return this.idjoaProduto;
    }
    
    public void setIdjoaProduto(int idjoaProduto) {
        this.idjoaProduto = idjoaProduto;
    }

    
    @Column(name="joa_nome", nullable=false, length=45)
    public String getJoaNome() {
        return this.joaNome;
    }
    
    public void setJoaNome(String joaNome) {
        this.joaNome = joaNome;
    }

    
    @Column(name="joa_descricao", nullable=false, length=250)
    public String getJoaDescricao() {
        return this.joaDescricao;
    }
    
    public void setJoaDescricao(String joaDescricao) {
        this.joaDescricao = joaDescricao;
    }

    
    @Column(name="joa_valorCompra", nullable=false, precision=10)
    public double getJoaValorCompra() {
        return this.joaValorCompra;
    }
    
    public void setJoaValorCompra(double joaValorCompra) {
        this.joaValorCompra = joaValorCompra;
    }

    
    @Column(name="joa_valorVenda", nullable=false, precision=10)
    public double getJoaValorVenda() {
        return this.joaValorVenda;
    }
    
    public void setJoaValorVenda(double joaValorVenda) {
        this.joaValorVenda = joaValorVenda;
    }

    
    @Column(name="joa_categoria", nullable=false)
    public int getJoaCategoria() {
        return this.joaCategoria;
    }
    
    public void setJoaCategoria(int joaCategoria) {
        this.joaCategoria = joaCategoria;
    }



}


