package bean;
// Generated 22/09/2023 23:07:42 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JoaProduto generated by hbm2java
 */
@Entity
@Table(name="joa_produto"
    ,catalog="db_julia_almada"
)
public class JoaProduto  implements java.io.Serializable {


     private int idjoaProduto;
     private String joaNome;
     private String joaDescricao;
     private double joaValorUnitario;
     private int joaCategoria;

    public JoaProduto() {
    }

	
    public JoaProduto(int idjoaProduto, String joaNome, String joaDescricao, double joaValorUnitario, int joaCategoria) {
        this.idjoaProduto = idjoaProduto;
        this.joaNome = joaNome;
        this.joaDescricao = joaDescricao;
        this.joaValorUnitario = joaValorUnitario;
        this.joaCategoria = joaCategoria;
    }
 
     @Id 

    
    @Column(name="idjoa_produto", unique=true, nullable=false)
    public int getIdjoaProduto() {
        return this.idjoaProduto;
    }
    
    public void setIdjoaProduto(int idjoaProduto) {
        this.idjoaProduto = idjoaProduto;
    }

    
    @Column(name="joa_nome", nullable=false, length=45)
    public String getJoaNome() {
        return this.joaNome;
    }
    
    public void setJoaNome(String joaNome) {
        this.joaNome = joaNome;
    }

    
    @Column(name="joa_descricao", nullable=false, length=250)
    public String getJoaDescricao() {
        return this.joaDescricao;
    }
    
    public void setJoaDescricao(String joaDescricao) {
        this.joaDescricao = joaDescricao;
    }


    
    @Column(name="joa_valorUnitario", nullable=false, precision=10)
    public double getJoaValorUnitario() {
        return this.joaValorUnitario;
    }
    
    public void setJoaValorUnitario(double joaValorUnitario) {
        this.joaValorUnitario = joaValorUnitario;
    }

    
    @Column(name="joa_categoria", nullable=false)
    public int getJoaCategoria() {
        return this.joaCategoria;
    }
    
    public void setJoaCategoria(int joaCategoria) {
        this.joaCategoria = joaCategoria;
    }

@Override
    public String toString(){
    return this.getJoaNome();
    }
    @Override
    public boolean equals (Object object){
    if(object instanceof JoaProduto){
        JoaProduto joaProduto = (JoaProduto) object;
    if(this.getIdjoaProduto()==joaProduto.getIdjoaProduto()){
    return true;
    } }
    return false;
}
 

}


