package bean;
// Generated 16/09/2023 15:42:58 by Hibernate Tools 4.3.1


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JoaUsuario generated by hbm2java
 */
@Entity
@Table(name="joa_usuario"
    ,catalog="db_juliaalmada"
)
public class JoaUsuario  implements java.io.Serializable {


     private int idjoaUsuario;
     private String joaNome;
     private String joaNickname;
     private String joaCpf;
     private Date joaDataNascimento;
     private String joaSenha;
     private int joaNivel;
     private String joaAtivo;

    public JoaUsuario() {
    }

    public JoaUsuario(int idjoaUsuario, String joaNome, String joaNickname, String joaCpf, Date joaDataNascimento, String joaSenha, int joaNivel, String joaAtivo) {
       this.idjoaUsuario = idjoaUsuario;
       this.joaNome = joaNome;
       this.joaNickname = joaNickname;
       this.joaCpf = joaCpf;
       this.joaDataNascimento = joaDataNascimento;
       this.joaSenha = joaSenha;
       this.joaNivel = joaNivel;
       this.joaAtivo = joaAtivo;
    }
   
     @Id 

    
    @Column(name="idjoa_usuario", unique=true, nullable=false)
    public int getIdjoaUsuario() {
        return this.idjoaUsuario;
    }
    
    public void setIdjoaUsuario(int idjoaUsuario) {
        this.idjoaUsuario = idjoaUsuario;
    }

    
    @Column(name="joa_nome", nullable=false, length=45)
    public String getJoaNome() {
        return this.joaNome;
    }
    
    public void setJoaNome(String joaNome) {
        this.joaNome = joaNome;
    }

    
    @Column(name="joa_nickname", nullable=false, length=45)
    public String getJoaNickname() {
        return this.joaNickname;
    }
    
    public void setJoaNickname(String joaNickname) {
        this.joaNickname = joaNickname;
    }

    
    @Column(name="joa_cpf", nullable=false, length=14)
    public String getJoaCpf() {
        return this.joaCpf;
    }
    
    public void setJoaCpf(String joaCpf) {
        this.joaCpf = joaCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="joa_dataNascimento", nullable=false, length=10)
    public Date getJoaDataNascimento() {
        return this.joaDataNascimento;
    }
    
    public void setJoaDataNascimento(Date joaDataNascimento) {
        this.joaDataNascimento = joaDataNascimento;
    }

    
    @Column(name="joa_senha", nullable=false, length=45)
    public String getJoaSenha() {
        return this.joaSenha;
    }
    
    public void setJoaSenha(String joaSenha) {
        this.joaSenha = joaSenha;
    }

    
    @Column(name="joa_nivel", nullable=false)
    public int getJoaNivel() {
        return this.joaNivel;
    }
    
    public void setJoaNivel(int joaNivel) {
        this.joaNivel = joaNivel;
    }

    
    @Column(name="joa_ativo", nullable=false, length=1)
    public String getJoaAtivo() {
        return this.joaAtivo;
    }
    
    public void setJoaAtivo(String joaAtivo) {
        this.joaAtivo = joaAtivo;
    }


}


