package bean;
// Generated 22/09/2023 22:28:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JoaVendaProduto generated by hbm2java
 */
@Entity
@Table(name="joa_venda_produto"
    ,catalog="db_juliaalmada"
)
public class JoaVendaProduto  implements java.io.Serializable {


     private int idjoaVendaProduto;
     private JoaProduto joaProduto;
     private JoaVenda joaVenda;
     private String joaQuantidade;
     private double joaValorUnitario;

    public JoaVendaProduto() {
    }

    public JoaVendaProduto(int idjoaVendaProduto, JoaProduto joaProduto, JoaVenda joaVenda, String joaQuantidade, double joaValorUnitario) {
       this.idjoaVendaProduto = idjoaVendaProduto;
       this.joaProduto = joaProduto;
       this.joaVenda = joaVenda;
       this.joaQuantidade = joaQuantidade;
       this.joaValorUnitario = joaValorUnitario;
    }
   
     @Id 

    
    @Column(name="idjoa_venda_produto", unique=true, nullable=false)
    public int getIdjoaVendaProduto() {
        return this.idjoaVendaProduto;
    }
    
    public void setIdjoaVendaProduto(int idjoaVendaProduto) {
        this.idjoaVendaProduto = idjoaVendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="joa_produto", nullable=false)
    public JoaProduto getJoaProduto() {
        return this.joaProduto;
    }
    
    public void setJoaProduto(JoaProduto joaProduto) {
        this.joaProduto = joaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="joa_venda", nullable=false)
    public JoaVenda getJoaVenda() {
        return this.joaVenda;
    }
    
    public void setJoaVenda(JoaVenda joaVenda) {
        this.joaVenda = joaVenda;
    }

    
    @Column(name="joa_quantidade", nullable=false, length=45)
    public String getJoaQuantidade() {
        return this.joaQuantidade;
    }
    
    public void setJoaQuantidade(String joaQuantidade) {
        this.joaQuantidade = joaQuantidade;
    }

    
    @Column(name="joa_valorUnitario", nullable=false, precision=10)
    public double getJoaValorUnitario() {
        return this.joaValorUnitario;
    }
    
    public void setJoaValorUnitario(double joaValorUnitario) {
        this.joaValorUnitario = joaValorUnitario;
    }




}


